export const data = {
  user: {
    name: "Noppadon Raksasiripong",
    image:
      "https://firebasestorage.googleapis.com/v0/b/chata-6a69a.appspot.com/o/portfolio%2FIMG-2938.JPG?alt=media&token=4415aa83-26cc-4095-8062-ca0bf4616252",
    tagline: "Full-Stack Web Developer(Reactjs, Nextjs, Nodejs)",
    location: "Bangkok,Thailand",
    email: "noppadol.raksa@gmail.com",
    github: "github.com/noppadolraksa",
    website: "www.linkedin.com/in/noppadolbright",
    strength: "Fast Learner",
    englishSkill: "Intermediate",
    born: "January 8th 1995",
    objective:
      "A passionate web developer who had experience in sales and marketing with ability to learn and collaborate in rapidly changing environments. Learned through freecodecamp and more for building projects from scratch. I am a fast learner with strong time management and hard worker.",
    phone: "0875606096",
    frontEndSkills: [
      "Reactjs",
      "Nextjs",
      "Html",
      "Css",
      "Javascript",
      "Typescript",
      "Redux",
      "Context API",
      "Styled-component",
      "Tailwind",
      "Firebase",
    ],
    backEndSkills: [
      "NodeJs",
      "ExpressJs",
      "Graphql",
      "Mongodb",
      "SQL",
      "Prisma",
      "Authentication & Authorization",
      "Redis",
      "Socket.io",
      "Web Security",
    ],
    infrastructures: ["Docker", "Heroku", "Github"],
  },
  project: [
    {
      title: "E-Commerce(29pages)",
      description:
        "MERN Stack B2C E-commerce from scratch with mobile responsively. these are the online retail stores that either sale products from their own brand or sell a variety of brands. there is admin dashboard for manage their users, products, and order with user's enquiry.",
      technologies: [
        "ReactJS",
        "Redux",
        "Redux-persist",
        "Styled-components",
        "MUI",
        "React-hook-form",
        "Axios",
        "Firebase-Storage",
        "Stripe",
        "ExpressJS",
        "Dotenv",
        "Mongoose",
        "Cors",
        "Nodemon",
        "Jsonwebtoken",
        "CrtyptoJS",
        "Docker",
      ],
      techniques: [
        "Login/registration",
        "State management(redux)",
        "Authentication(JWT) & authorization(User or Admin)",
        "Responsive (mobile, tablet, PC)",
        "Form with error handling",
        "Data visualization(charts & tables)",
        "Payment(stripe)",
        "Dockerize",
        "Dashboard(monthly reports & user reports & order list)",
      ],
      sourceCode: "https://github.com/noppadolraksa",
      link1: "https://my-shop-e-commerce.netlify.app",
      link2: "https://my-shop-admin.netlify.app",
      link3: "https://prezi.com/p/e8h1eijgkuo1/?present=1",
      finished: true,
    },
    {
      title: "Portfolio",
      description:
        "Nextjs with GraghQL, Nexus, Apollo,Prisma, PostgreSQL and Typescript",
      technologies: [
        "NextJs",
        "Prisma",
        "Apollo",
        "Nexus",
        "GraphQL",
        "PostgreSQL",
        "Typescript",
        "Styled-component",
        "Next-themes",
      ],
      techniques: [
        "Dark-mode",
        "Seeding data",
        "Type-safe with Nexus schema",
        "Nested Comments(tree-like structure)",
      ],
      sourceCode: "https://github.com/noppadolraksa/portfolio",
      finished: true,
    },
    {
      title: "Serverless chat app",
      description: "Serverless Nextjs with firebase, tailwind and typescript",
      technologies: [
        "NextJs",
        "React-hook-form",
        " Firebase-authentucation",
        " Firestore",
        "Tailwind",
        " Antd",
      ],
      techniques: [
        "login-register with firebase authentication",
        "cool UI with antd and tailwind",
        "Update realtime chatapp,Form handling,",
        "upload image",
      ],
      sourceCode: "https://github.com/noppadolraksa/nextchatapp",
      link1: "https://nextchatapp-noppadolraksa.vercel.app",
      finished: true,
    },
  ],
  education: [
    {
      degree: "High School",
      institution: "Wat Nuan Noradit School",
      date: "2006-2012",
      fieldOfStudy: "Math&Science",
    },
    {
      degree: "Bachelor Degree",
      institution: "Faculty of Economics Thammasat University",
      date: "2013-2017",
      fieldOfStudy: "Business, International Business",
    },
    {
      degree: "Codecamp",
      institution: "Freecodecamp",
      date: "present",
      fieldOfStudy: "html,css,javascript,data-structure,algorithms",
    },
  ],
  skill: {
    reading: 5,
    writing: 3,
    speaking: 3,
    listening: 4,
    communicating: 5,
    personalities: [
      "Humble",
      "Flexible",
      "Hard-working",
      "Creative",
      "Problem-solving",
      "Open-mined",
      "Passionate",
    ],
  },
  experience: [
    {
      title: "Assistant of product manager",
      company: "AAC & TRW Asiatic Co, Ltd,",
      startDate: "04-2016",
      endDate: "08-2016",
      employmentType: "Trainee",
      description:
        "summary email from each supplier, planning stock control,designing excel condition as a request, adjusting database to be cleaner",
    },
    {
      title: "Sales Executive",
      company: "LDT Microprecision",
      startDate: "10-2017",
      endDate: "01-2019",
      employmentType: "Full-Time",
      description:
        "Trained about the product semiconductor tools at Penang for 2 weeks. Market company products to their multinational company (End user+Purchasing). Make and arrange an appointment for presentation and meeting. Work with overseas. Generate and attend to customers enquiries and maintain good relationship with customers. Promote company new products to their customers",
    },
    {
      title: "Grocery store",
      company: "Family business",
      startDate: "02-2019",
      endDate: "01-2021",
      employmentType: "Family business",
      description: "",
    },
    {
      title: "food delivery",
      company: "Jaw Pon Fire",
      startDate: "01-2021",
      endDate: "present",
      employmentType: "Owner",
      description: "",
      link1: "https://lin.ee/BkjeJ9A",
    },
  ],
};
