/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./context"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  EducationOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ProjectOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  SkillOrderByWithRelationInput: { // input type
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    index?: NexusGenEnums['SortOrder'] | null; // SortOrder
    listening?: NexusGenEnums['SortOrder'] | null; // SortOrder
    personalities?: NexusGenEnums['SortOrder'] | null; // SortOrder
    reading?: NexusGenEnums['SortOrder'] | null; // SortOrder
    speaking?: NexusGenEnums['SortOrder'] | null; // SortOrder
    user?: NexusGenInputs['UserOrderByWithRelationInput'] | null; // UserOrderByWithRelationInput
    userId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    writing?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserOrderByWithRelationInput: { // input type
    backEndSkills?: NexusGenEnums['SortOrder'] | null; // SortOrder
    born?: NexusGenEnums['SortOrder'] | null; // SortOrder
    education?: NexusGenInputs['EducationOrderByRelationAggregateInput'] | null; // EducationOrderByRelationAggregateInput
    email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    englishSkill?: NexusGenEnums['SortOrder'] | null; // SortOrder
    frontEndSkills?: NexusGenEnums['SortOrder'] | null; // SortOrder
    github?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    image?: NexusGenEnums['SortOrder'] | null; // SortOrder
    index?: NexusGenEnums['SortOrder'] | null; // SortOrder
    infrastructures?: NexusGenEnums['SortOrder'] | null; // SortOrder
    location?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    objective?: NexusGenEnums['SortOrder'] | null; // SortOrder
    phone?: NexusGenEnums['SortOrder'] | null; // SortOrder
    project?: NexusGenInputs['ProjectOrderByRelationAggregateInput'] | null; // ProjectOrderByRelationAggregateInput
    skill?: NexusGenInputs['SkillOrderByWithRelationInput'] | null; // SkillOrderByWithRelationInput
    strength?: NexusGenEnums['SortOrder'] | null; // SortOrder
    tagline?: NexusGenEnums['SortOrder'] | null; // SortOrder
    website?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserWhereUniqueInput: { // input type
    id?: string | null; // String
  }
}

export interface NexusGenEnums {
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Education: { // root type
    date?: string | null; // String
    degree: string; // String!
    fieldOfStudy: string; // String!
    id: string; // String!
    index: number; // Int!
    institution: string; // String!
    userId: string; // String!
  }
  Project: { // root type
    description: string; // String!
    finished: boolean; // Boolean!
    id: string; // String!
    index: number; // Int!
    link1?: string | null; // String
    link2?: string | null; // String
    link3?: string | null; // String
    sourceCode?: string | null; // String
    techniques: string[]; // [String!]!
    technologies: string[]; // [String!]!
    title: string; // String!
    userId: string; // String!
  }
  Query: {};
  Skill: { // root type
    id: string; // String!
    listening: number; // Int!
    personalities: string[]; // [String!]!
    reading: number; // Int!
    speaking: number; // Int!
    userId: string; // String!
    writing: number; // Int!
  }
  User: { // root type
    backEndSkills: string[]; // [String!]!
    born: string; // String!
    email: string; // String!
    englishSkill: string; // String!
    frontEndSkills: string[]; // [String!]!
    github: string; // String!
    id: string; // String!
    image: string; // String!
    index: number; // Int!
    infrastructures: string[]; // [String!]!
    location: string; // String!
    name: string; // String!
    objective: string; // String!
    phone: string; // String!
    strength: string; // String!
    tagline: string; // String!
    website: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Education: { // field return type
    date: string | null; // String
    degree: string; // String!
    fieldOfStudy: string; // String!
    id: string; // String!
    index: number; // Int!
    institution: string; // String!
    user: NexusGenRootTypes['User']; // User!
    userId: string; // String!
  }
  Project: { // field return type
    description: string; // String!
    finished: boolean; // Boolean!
    id: string; // String!
    index: number; // Int!
    link1: string | null; // String
    link2: string | null; // String
    link3: string | null; // String
    sourceCode: string | null; // String
    techniques: string[]; // [String!]!
    technologies: string[]; // [String!]!
    title: string; // String!
    user: NexusGenRootTypes['User']; // User!
    userId: string; // String!
  }
  Query: { // field return type
    user: Array<NexusGenRootTypes['User'] | null>; // [User]!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  Skill: { // field return type
    id: string; // String!
    listening: number; // Int!
    personalities: string[]; // [String!]!
    reading: number; // Int!
    speaking: number; // Int!
    userId: string; // String!
    writing: number; // Int!
  }
  User: { // field return type
    backEndSkills: string[]; // [String!]!
    born: string; // String!
    education: Array<NexusGenRootTypes['Education'] | null>; // [Education]!
    email: string; // String!
    englishSkill: string; // String!
    frontEndSkills: string[]; // [String!]!
    github: string; // String!
    id: string; // String!
    image: string; // String!
    index: number; // Int!
    infrastructures: string[]; // [String!]!
    location: string; // String!
    name: string; // String!
    objective: string; // String!
    phone: string; // String!
    project: Array<NexusGenRootTypes['Project'] | null>; // [Project]!
    skill: NexusGenRootTypes['Skill'] | null; // Skill
    strength: string; // String!
    tagline: string; // String!
    website: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Education: { // field return type name
    date: 'String'
    degree: 'String'
    fieldOfStudy: 'String'
    id: 'String'
    index: 'Int'
    institution: 'String'
    user: 'User'
    userId: 'String'
  }
  Project: { // field return type name
    description: 'String'
    finished: 'Boolean'
    id: 'String'
    index: 'Int'
    link1: 'String'
    link2: 'String'
    link3: 'String'
    sourceCode: 'String'
    techniques: 'String'
    technologies: 'String'
    title: 'String'
    user: 'User'
    userId: 'String'
  }
  Query: { // field return type name
    user: 'User'
    users: 'User'
  }
  Skill: { // field return type name
    id: 'String'
    listening: 'Int'
    personalities: 'String'
    reading: 'Int'
    speaking: 'Int'
    userId: 'String'
    writing: 'Int'
  }
  User: { // field return type name
    backEndSkills: 'String'
    born: 'String'
    education: 'Education'
    email: 'String'
    englishSkill: 'String'
    frontEndSkills: 'String'
    github: 'String'
    id: 'String'
    image: 'String'
    index: 'Int'
    infrastructures: 'String'
    location: 'String'
    name: 'String'
    objective: 'String'
    phone: 'String'
    project: 'Project'
    skill: 'Skill'
    strength: 'String'
    tagline: 'String'
    website: 'String'
  }
}

export interface NexusGenArgTypes {
  Query: {
    users: { // args
      after?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      before?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['UserOrderByWithRelationInput'][] | null; // [UserOrderByWithRelationInput!]
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}